### ISSUE TITLE
Highlighting issues/inconsistenties

### ISSUE THREAD

**Issue by radrow** [aeternity/aesophia-vscode#1]
For example 
```
function f() =
  let
```
will not color `let` until I add the variable name.

Similarly, `include` is not colored if it's indented.

`interface` is colored only right after `contract`. There must be no newlines on the way. I think it should always get the keyword color, because it's not usable anywhere else. Also, `main` is always colored.

`datatype` name and `record` name are colored differently. Moreover, `record` name is colored differently when it has or doesn't have parameters. `type` aliases have yet different color.

Some delimiters and operators such as `|` or `<-` are not colored. Not sure how important it is, though. 

`[]` and `()` are colored the same way. This shouldn't be the case imo, because square brackets are (almost?) always expressions, while `()` and `{}` are delimiters.

I think variables should be colored the same as function names in expressions. For instance
```
1. let x = () => 3
2. x
3. x() 
```
I don't see a reason for `x` to have a different color in 2 and 3. In 1 it is a separate case, because it's introduction, so it may be different. Also observe that upper-ids are colored the same regardless whether there are parentheses around or not.

Type variables (`'a`) deserve some color imo.

**Comment by ghallak** [comment]
> will not color let until I add the variable name.

This was fixed.

> Similarly, include is not colored if it's indented.

This was fixed for includes along with pragmas.

> interface is colored only right after contract. There must be no newlines on the way. I think it should always get the keyword color, because it's not usable anywhere else. Also, main is always colored.

This was fixed.

> datatype name and record name are colored differently. Moreover, record name is colored differently when it has or doesn't have parameters. type aliases have yet different color.

Now all `datatype`, `type`, and `record` names have the same color.

> Some delimiters and operators such as | or <- are not colored. Not sure how important it is, though.

These are marked correctly, but there is no color in my vscode current theme for them, so I think they will stay white for now.

> [] and () are colored the same way. This shouldn't be the case imo, because square brackets are (almost?) always expressions, while () and {} are delimiters.

I don't think we should color brackets differently, I think different coloring of brackets should be used for nesting (e.g. [[1,2], [3,4]] the level 1 brackets and level 2 brackets have different color).

> I think variables should be colored the same as function names in expressions. For instance

I would like the coloring to distinguish between variables and functions, currently it's not possible to differentiate between variables and functions because we don't have semantic highlighting, but once we have it, you should be able to tell by the color if you're looking at a local variable or a function name. Right now, all function calls are assumed to be function names.

> Also observe that upper-ids are colored the same regardless whether there are parentheses around or not.

Upper ids are type constructors regardless of whether they have paraentheses or not, that's why they have the same color.

> Type variables ('a) deserve some color imo.

They have a color now.

**Comment by radrow** [comment]
> I would like the coloring to distinguish between variables and functions

Sophia it's functional, so there shouldn't be any practical difference

**Comment by ghallak** [comment]
Done here 7c84494ac73ae9e801d73572d5a1c45103dac6a2.
